### ISSUE TITLE
Support for GitLab

### ISSUE THREAD

**Issue by Turbo87** [Financial-Times/github-label-sync#10]
While the project name suggests that this is only meant to be used with GitHub it would be quite nice to make it work with GitLab too. Since labels work roughly the same in both platforms it shouldn't be that difficult to do, but I guess then we would likely have to rename the project.

If this sounds interesting to you please let me know then I'll start working on this.

/cc @rowanmanning

**Comment by JakeChampion** [comment]
I don't think we would be supporting GitLab as we do not use GitLab ourselves and would not know if we ever broke the GitLab functionality.

Feel free to make a fork of this project that supports GitLab as well as GitHub, the code is licensed under MIT which allows for you to copy the code and modify it to your needs :)
