### ISSUE TITLE
allow for setting access token from file

### ISSUE THREAD

**Issue by jgehrcke** [Financial-Times/github-label-sync#113]
Having the access token pop up literally in the command line is a common security pitfall.

For background, I like https://www.netmeister.org/blog/passing-passwords.html.

Major takeaway: "Allow passing of the secret from a file".

Other refs:
https://github.com/FreeRDP/FreeRDP/issues/3639
https://stackoverflow.com/questions/3830823/hiding-secret-from-command-line-parameter-on-unix

**Comment by JakeChampion** [comment]
It's also able to be set via an environment variable named `GITHUB_ACCESS_TOKEN`.

If you want to implement this feature, I'd be happy to review the pull-request and look at merging it into the project.

I'm going to close this issue as it is not a feature we are looking to implement and the project already has a safer way for setting the token.

**Comment by jgehrcke** [comment]
Oh, I indeed missed that part in the README:

> On the command-line this can be set with either the access-token flag or the GITHUB_ACCESS_TOKEN environment variable

Yeah, that's already a little better, although (as the article I first linked above also points out) reading sensitive data from a file is always preferable. 

Thanks for the feedback!
