### ISSUE TITLE
Merging labels doesn't seem to work

### ISSUE THREAD

**Issue by Turbo87** [Financial-Times/github-label-sync#12]
If the repo contains labels `a` and `b` and my config defines label `a` with a different color and `aliases: ['b']` then the script will only change the color of `a`, but not touch `b` at all.

This is probably a limitation of the underlying API, but maybe it is possible to work around it? I'm not sure if that is viable, but reassigning all issues with label `b` to label `a` and then delete label `b` might be an option 🤔

**Comment by rowanmanning** [comment]
> I'm not sure if that is viable, but reassigning all issues with label b to label a and then delete label b might be an option 🤔
Yeah I think I agree with this approach most, but I don't think it'd be particularly easy to implement merging of labels like this. I'd accept a PR, but unlikely to implement ourselves at the moment

**Comment by chee** [comment]
we don't have capacity for this, and this issue is 3 years old.

this isn't something we need, and as such isn't something we can support. 

a PR for this would probably be accepted, but it's not something we are going to timetable so i'm going to close the issue.
