### ISSUE TITLE
Fetching labels from GitHub -> label.toLowerCase is not a function

### ISSUE THREAD

**Issue by shiipou** [Financial-Times/github-label-sync#121]
[Bug]
---

## What

At the `Fetching labels from GitHub` step,
The node app raise an error `TypeError: label.toLowerCase is not a function`.

## Details

You can check the repository that contain all my work on the branch named `change-techno` [here](https://github.com/shiipou/labelset/tree/efeaf920d95105931e567253f8baa5ea7c5c72ea)
There is a YAML file that contain the labels I use.

I tried to apply them with the following command : _(labels.yaml is a file located in /home/user/labels.yaml)_
```bash
github-label-sync --access-token 7******1  --labels ./labels.yaml shiipou/labelset
```

Here the error raised : 
```bash
Syncing labels for "shiipou/labelset"
Fetching labels from GitHub
TypeError: label.toLowerCase is not a function
    at /Users/flavien.cadet/.nvm/versions/node/v12.18.3/lib/node_modules/github-label-sync/lib/calculate-label-diff.js:15:78
    at Array.map (<anonymous>)
    at /Users/flavien.cadet/.nvm/versions/node/v12.18.3/lib/node_modules/github-label-sync/lib/calculate-label-diff.js:15:59
    at Array.filter (<anonymous>)
    at /Users/flavien.cadet/.nvm/versions/node/v12.18.3/lib/node_modules/github-label-sync/lib/calculate-label-diff.js:11:33
    at Array.forEach (<anonymous>)
    at calculateLabelDiff (/Users/flavien.cadet/.nvm/versions/node/v12.18.3/lib/node_modules/github-label-sync/lib/calculate-label-diff.js:8:19)
    at /Users/flavien.cadet/.nvm/versions/node/v12.18.3/lib/node_modules/github-label-sync/lib/github-label-sync.js:41:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by chee** [comment]
hey! i think this is happening because one of your aliases is being parsed as an object rather than a string: https://github.com/shiipou/labelset/blob/efeaf920d95105931e567253f8baa5ea7c5c72ea/labels.yaml#L13

isn't yaml just a joy

we should be printing a better error here, though, so i'm going to leave this ticket open until we fix that :)

thank you for bringing it to our attention

**Comment by shiipou** [comment]
> hey! i think this is happening because one of your aliases is being parsed as an object rather than a string: https://github.com/shiipou/labelset/blob/efeaf920d95105931e567253f8baa5ea7c5c72ea/labels.yaml#L13
> 
> isn't yaml just a joy
> 
> we should be printing a better error here, though, so i'm going to leave this ticket open until we fix that :)
> 
> thank you for bringing it to our attention

Oh ok, Haven't see this on my code editor.
