### ISSUE TITLE
Validation Failed error when there is more than one alias

### ISSUE THREAD

**Issue by designsimply** [Financial-Times/github-label-sync#149]
Steps to reproduce:

1. Have a repo that contains the labels "Broken Tests" and "Tests".
1. Create a label config file and include the sample below.
1. Run the script.
1. Run the script again.

Sample label config:

```
    {
        "name": "category: tests",
        "color": "3e4b9e",
        "aliases": [
            "Broken Tests",
            "Tests"
        ],
        "description": "Related to any kind of testing."
    }
```

**Result:** the second alias is never updated and the following error appears if the script has been executed at least once before:

```
GitHub Error:
PATCH /repos/myname/myrepo/labels/Tests
422: Validation Failed
```

<sup>Tested with github-label-sync 2.0.0 using `--allow-added-labels` on macOS 10.15.6 with Node.js v16.0.0 (also tried with v12.22.1).</sup>

**Comment by designsimply** [comment]
Thanks for your work on this btw! ❤️

**Comment by JuKu** [comment]
I get the same error.
