### ISSUE TITLE
Support leading `#` in hexadecimal color strings

### ISSUE THREAD

**Issue by carlo-quinonez** [Financial-Times/github-label-sync#152]
Feature: Support the leading `#` when specifying label colors

## What
Currently colors are specified in the same format that's expected by the GitHub API - without a leading `#`. 

## Details
I'd like to see the color preview in VSCode when I'm editing the yaml files. There are plugins for VSCode
that automatically colorize hex color strings that start with a `#`. 

![image](https://user-images.githubusercontent.com/53790047/120697138-36ca5180-c462-11eb-9789-4305414d23d5.png)

It would be easy to strip a leading `#` from the color string if present.

## Additional information
I can submit a PR for this.

**Comment by chee** [comment]
#153

**Comment by danielwerg** [comment]
Shouldn't this be removed from readme?

https://github.com/Financial-Times/github-label-sync/blob/master/README.md?plain=1#L184
