### ISSUE TITLE
Support for description

### ISSUE THREAD

**Issue by yvele** [Financial-Times/github-label-sync#16]
That would be nice.

Label description is a new GitHub feature: https://blog.github.com/2018-02-22-label-improvements-emoji-descriptions-and-more/

> Add descriptions to your labels to provide even more context and help your contributors apply the right ones to their issues or pull requests. Descriptions will appear when you hover your mouse over labels around GitHub.

API documentation
 - https://developer.github.com/v3/issues/labels/#parameters
 - https://developer.github.com/changes/2018-02-22-label-description-search-preview/

Related to https://github.com/popomore/github-labels/issues/26

**Comment by sgnn7** [comment]
@yvele I've looked into fixing this and it seems that GitHub label description API is still in preview mode and by default requires a specific header (`Accept: `) that octonode (module for interacting with GH APIs) just [doesn't use](https://github.com/pksunkara/octonode/blob/master/src/octonode/client.coffee#L39) for it to work.

You can see more details here:
https://developer.github.com/changes/2018-02-22-label-description-search-preview/

I might try to add a workaround to this codebase with this line somewhere soon:
```
client.requestDefaults.headers.Accept = "application/vnd.github.symmetra-preview+json";
```

**Comment by sjawhar** [comment]
I built on @sgnn7 's branch to build this functionality: https://github.com/sjawhar/github-label-sync

**Comment by schickling** [comment]
Any update on this? 🙏

**Comment by JakeChampion** [comment]
Added in #19

**Comment by azu** [comment]
@JakeChampion Does 1.4.2 is published on npm?
