### ISSUE TITLE
Throw when not passing `labels`.

### ISSUE THREAD

**Issue by stagas** [Financial-Times/github-label-sync#17]
Invoking the function without passing the `labels` property, automatically assumes **no labels**, so it kills all existing labels in the target repository. Would be great if it threw an error instead.

**Comment by JakeChampion** [comment]
Sorry if the tool removed labels from one of your projects when you were trying it out.

The tool has a flag `--dry-run`, which will not make any changes to labels and would tell you what changes would have been made.

Not passing a values to the `--labels` flag would make it use the [default GitHub labels](https://github.com/Financial-Times/github-label-sync/blob/master/labels.json).

Passing no labels property to the function is the way to signify no labels on a project.
