### ISSUE TITLE
YAML support

### ISSUE THREAD

**Issue by schickling** [Financial-Times/github-label-sync#24]
It would be great if additionally to supporting `.json` files, YAML files (i.e. `.yml` and `.yaml`) would also be supported. This should be fairly simple to add.

**Comment by JakeChampion** [comment]
@schickling That sounds like a good feature, I think we would be happy to accept a pull-request that adds yaml support :-)

**Comment by schickling** [comment]
We've ended up implementing our own system https://github.com/maticzav/label-sync
