### ISSUE TITLE
Support for updating

### ISSUE THREAD

**Issue by benswinburne** [Financial-Times/github-label-sync#26]
Feature Request

## What

It'd be great if we could use the update api in order to change existing labels. At present if we don't allow changes to existing labels. For example renaming one in the labels.json file would lead to deletion of the old and creation of the new which subsequently removes the original label from any issues to which it was assigned.

## Details

What prompted the request
I renamed an issue in my labels.json under the assumption (foolishly) that it  would apply the change as an update to the existing label but obviously it didn't and it created a new label and removed the label from the existing issues.

Obviously it couldn't rename the issue without me providing the old name and the new name so i don't really know why I expected it. 

Given that the [API allows for PATCHing][1] labels using the :current_name in the URL, perhaps if we were to provide the :current_name with the label in labels.json we could update that label rather than deleting/adding.

For example
```
    {
        "name": "bug :bug:",
        "color": "9b221b",
        "aliases": [":bug:"],
        "current_name": "bug"
    },
```

I have a script which runs periodically and on ci on a label change which keeps all of the repos with issue support in sync so I don't really want to enable allow-added-labels as that'll allow the repos to get out of sync.

 [1]: https://developer.github.com/v3/issues/labels/#update-a-label

**Comment by benswinburne** [comment]
Just had a look through the code and it appears it does support updating but it doesn't seem to have worked when I'd done it previously. I'll retry this and come back as it may be a bug report instead of a feature request... or perhaps more likely me using it wrong.

**Comment by nesl247** [comment]
I am running into the same issue. `aliases` does not appear to be working at all.

**Comment by nesl247** [comment]
Figured out why it isn't working. The issue is this line https://github.com/Financial-Times/github-label-sync/blob/cc454d04e878ad6ab88247b81595ef485b9b4411/lib/calculate-label-diff.js#L15

If you look, it only supports `aliases` with lowercase names. Even if the label is mixed case, you MUST specify the alias as lowercase.
