### ISSUE TITLE
1.4.1 is not published on npm?

### ISSUE THREAD

**Issue by azu** [Financial-Times/github-label-sync#30]
## What
https://github.com/Financial-Times/github-label-sync/releases/tag/v1.4.1 is tagged. But 1.4.1 is not found on npm.

## Details

1.4.1 includes `description` support #16 

/cc @JakeChampion

**Comment by JakeChampion** [comment]
Yep, I'm having trouble publishing it as my npm account is not on the maintainers list for the package. An invitation has been sent to me but it has not shown up in my email inbox and the npm website does not expose the invite either (missing functionality). I'll update this ticket when it does get published.

**Comment by JakeChampion** [comment]
Version 1.4.1 is now on npm

**Comment by azu** [comment]
Thanks!
