### ISSUE TITLE
URL for POST broken? 

### ISSUE THREAD

**Issue by martinstreicher** [Financial-Times/github-label-sync#48]
I get the following when the tool tries to adjust the labels: 

```
GitHub Error:
POST /repos/martinstreicher/test/labels
404: Not Found
```

**Comment by shchedrakov** [comment]
I have the same error.
```bash
github-label-sync --access-token as8...12c -A --labels labels.yml projects/project
Syncing labels for "projects/project"
Fetching labels from GitHub
GitHub Error:
GET /repos/projects/project/labels
404: Not Found
```

**Comment by JakeChampion** [comment]
Hmm, it is working for all of repositories and we've not had anyone else mention this. Does it work for another repository you have?

**Comment by shchedrakov** [comment]
@martinstreicher I had the same error, but it was just my mistake. I set wrong access permission for my personal access token on Github. If you set repo and workflow permissions then It must be enough to sync labels between repos. 

![Screenshot 2020-06-05 at 18 29 31](https://user-images.githubusercontent.com/9498638/83894871-8cd6bd00-a75a-11ea-8a72-4f4028363817.png)

**Comment by SebastianOpriel** [comment]
Be aware that the user of the PAT, has write permissions to the repository
