### ISSUE TITLE
Enable multiple label files

### ISSUE THREAD

**Issue by kenperkins** [Financial-Times/github-label-sync#49]
I'd love to be able run with multiple labels files, but not using the `--allow-added-labels` flag:

```
github-label-sync --access-token xxxxx  --labels labels-common.json --labels labels-specific.json myorg/myrepo
```

This would allow me to have a standard set of labels I apply across repos, and repo-specific labeling, all in one execution, having confidence it can merge before validating, and then run as one process.

**Comment by JakeChampion** [comment]
That's a great idea @kenperkins!
We'd be happy to accept a pull-request for this feature :-)
