### ISSUE TITLE
Test failure: lib/github-label-sync githubLabelSync(options) when the `dryRun` option is `true` .then() should not execute any diff promises

### ISSUE THREAD

**Issue by chasenlehara** [Financial-Times/github-label-sync#5]
Steps to reproduce:

1. Clone the repo
2. `npm install`
3. `npm test`

Expected results: tests would pass

Actual results: test failure: `AssertError: notCalled takes 1 argument but was called with 2 arguments`

Environment: Node 6.9.1, npm 4.2.0

You can see the build failed here: https://circleci.com/gh/Financial-Times/github-label-sync/13

**Comment by chasenlehara** [comment]
I am taking a stab at fixing #1 so I thought a good first step was to run the tests after installing everything. I am not expecting this to be fixed with any urgency. If I could get some guidance on where `notCalled` is coming from (doesn’t look like from `proclaim`) I would be happy to fix it myself.

Thanks for the great project! 🙏

**Comment by JakeChampion** [comment]
This has been resolved in #6 , as has #4 :-)
