### ISSUE TITLE
Add an option to run for all repositories in a user or organisation

### ISSUE THREAD

**Issue by danth** [Financial-Times/github-label-sync#53]
## What

I sometimes find myself manually running `github-label-sync` on each of my repositories when I update my configuration file. It would be useful to be able to do that automatically.

## Details

A command-line option such as `--all-repos <user or org>`.

Essentially, just fetch a list of repositories within the given user or organisation and loop through them, running the program for each.

**Comment by chasenlehara** [comment]
Hi @AlphaMycelium, I haven’t touched this script in a while, but I wrote a script that probably does what you’re looking for: https://github.com/donejs/developer-relations/blob/a70c8deb269a25bd490720e951b9770866339727/sync-labels.js

[Sorry, no docs and no support if it doesn’t do what you’re looking for.]

**Comment by JakeChampion** [comment]
Hi @AlphaMycelium, this is not a feature that we actively had a need for. We chose to instead make a GitHub Action to sync our labels across our repositories for us -- https://github.com/Financial-Times/origami-labels

If you are able to add this feature to the project along with some tests to show it works, we would accept the request :-)

**Comment by AlphaMycelium** [comment]
I found that a slightly adjusted version of @chasenlehara's script worked for me, so there isn't a need to add it at the moment. However I think it's best to leave this issue open.

**Comment by chee** [comment]
This request is out of scope for this project
